### ISSUE TITLE
Ошибка при переводе из вещ в нат

### ISSUE THREAD

**Issue by egorbabushka** [tsoding/good_training_language#1]
следующаяя строка кода выводит 18446744073709551489, хотя явно не должна:
```хуя
печать((255.0 - 128.0) как нат, "\н");
```
при чем
```хуя
печать(255.0 как нат, "\н");
```
и
```хуя
печать((55.0 - 128.0) как нат, "\н");
```
ведут себя вполне нормально

**Comment by rexim** [comment]
Ага, ну видимо я опять с порядком аргументов ошибся... Спасибо, я посмотрю!
