### ISSUE TITLE
Два гения

### ISSUE THREAD

**Issue by x1z53** [tsoding/good_training_language#5]
Я тут буквально 4 апреля представил свой язык, который писал также, как и ты, 4 месяца

Совпадение? Однозначно

Я только подступил к компиляции, так что буду у тебя списывать (ну, разумеется не точь-в-точь)

Если интересно
https://gitverse.ru/x1z53/korsakov

**Comment by rexim** [comment]
Ишуй не имеет отношения к проекту.
